server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: log
    static_configs:
      - targets:
          - localhost
        labels:
          job: log
          __path__: /var/log/*.log
