version: "3"

services:
  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    ports:
      - "1514:1514"
    volumes:
      - ./config.yaml:/etc/promtail/config.yaml
      - ./data:/tmp/promtail
      - ./log:/var/log
    command: -config.file=/etc/promtail/config.yaml --client.external-labels=hostname=${HOSTNAME}
